package tdas.vector;

import java.util.Collection;
import java.util.List;
import java.util.Comparator;
import java.util.Iterator;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.function.UnaryOperator;

public interface Vector<E> {
    boolean add(E e);
    void add(int index, E element);
    boolean addAll(Collection<? extends E> c);
    boolean addAll(int index, Collection<? extends E> c);
    void addElement(E obj);
    int capacity();
    void clear();
    Object clone();
    boolean contains(Object o);
    boolean containsAll(Collection<E> c);
    void copyInto(Object[] arr);
    E elementAt(int index);
    void ensureCapacity(int minCapacity);
    boolean equals(Object o);
    E firstElement();
    void forEach(Consumer<? super E> action);
    E get(int index);
    int hashCode();
    int indexOf(E e);
    int indexOf(E e, int index);
    void insertElementAt(E e, int index);
    boolean isEmpty();
    Iterator<E> iterator();
    E lastElement();
    int lastIndexOf(E e);
    int lastIndexOf(E e, int index);
    E remove(int index);
    boolean remove(E e);
    boolean removeAll(Collection<E> c);
    void removeAllElements();
    boolean removeElement(Object e);
    void removeElementAt(int index);
    boolean removeIf(Predicate<? super E> filter);
    void replaceAll(UnaryOperator<E> operator);
    boolean retainAll(Collection<E> c);
    E set(int index, E element);
    void setElementAt(E e, int index);
    int size();
    void sort(Comparator<? super E> c);
    List<E> subList(int fromIndex, int toIndex);
    Object[] toArray();
    String toString();
}
