@startuml
class Resto {
-mesas: MesaDeResto[]
-maximaPropinaRegistrada: double
+solicitarMesa(): int
+cerrarMesa(int numeroDeMesa, double propina): int
+mesaConMasPropina(): int
+totalPropinas(): double
}

class MesaDeResto {
-numero: int
-propinaAcumulada: double
-estadoDeLaMesa: EstadoDeMesaDeResto
+ocupar(): void
+cerrar(propina): int
-liberar(): void
+estaLibre(): boolean
}

enum EstadoDeMesaDeResto {
LIBRE,
OCUPADA,
}
@enduml